name: Pull Request
on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]
jobs:
  RunTests:
    runs-on: [self-hosted, linux, x64, bwstaging]
    steps:
      # Setup
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          mask-aws-account-id: false
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Test
      - name: Test with rake
        run: bundle exec rake
